config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :invoices

  get 'home/index'

    root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
belongs_to :customers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:companny, :name, :surname, :address_street, :address_city, :address_zipcode, :ic, :dic, :contact, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:user_id, :date_created, :date, :payment_date, :payment_type, :amount, :items, :note)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :companny, 'Firma' %><br>
    <%= f.text_field :companny %>
  </div>
  <h4>Kontaktní osoba</h4>
  <div class="field">
    <%= f.label :name, 'Jméno' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname, 'Příjmení' %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :address_street, 'Ulice' %><br>
    <%= f.text_field :address_street %>
  </div>
  <div class="field">
    <%= f.label :address_city, 'Město' %><br>
    <%= f.text_field :address_city %>
  </div>
  <div class="field">
    <%= f.label :address_zipcode, 'PSč' %><br>
    <%= f.text_field :address_zipcode %>
  </div>
  <div class="field">
    <%= f.label :ic, 'IČ' %><br>
    <%= f.text_field :ic %>
  </div>
  <div class="field">
    <%= f.label :dic, 'DIČ' %><br>
    <%= f.text_field :dic %>
  </div>
  <div class="field">
    <%= f.label :contact, 'Kontakt' %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :note, 'Poznámka' %><br>
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit 'Odeslat' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Přehled zákazníků</h1>

<table>
  <thead>
    <tr>
      <th>Firma</th>
      <th>Měto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.companny %></td>
        <td><%= customer.address_city %></td>
        <td><%= link_to 'Zobrazit', customer %></td>
        <td><%= link_to 'Upravit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Smazat', customer, method: :delete, data: { confirm: 'Opravdu chcete pokračovat?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nový zákazník', new_customer_path %>

app/views/customers/new.html.erb
<h1>Nový zákazník</h1>

<%= render 'form' %>

<%= link_to 'Zpět', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Firma:</strong>
  <%= @customer.companny %>
</p>
<h4>Kontaktní osoba</h4>
<p>
  <strong>Jméno:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Příjmení:</strong>
  <%= @customer.surname %>
</p>

<p>
  <strong>Ulice:</strong>
  <%= @customer.address_street %>
</p>

<p>
  <strong>Město:</strong>
  <%= @customer.address_city %>
</p>

<p>
  <strong>PSČ:</strong>
  <%= @customer.address_zipcode %>
</p>

<p>
  <strong>IČ:</strong>
  <%= @customer.ic %>
</p>

<p>
  <strong>DIČ:</strong>
  <%= @customer.dic %>
</p>

<p>
  <strong>Kontakt:</strong>
  <%= @customer.contact %>
</p>

<p>
  <strong>Poznámka:</strong>
  <%= @customer.note %>
</p>

<%= link_to 'Upravit', edit_customer_path(@customer) %> |
<%= link_to 'Zpět', customers_path %>

app/views/home/companies.html.erb
<h1>Nabídka pro firmy</h1>

<p>Poskytneme Vám nejen prostor, ale i komplexn ířešení zprávy Vašich dat. Dle varianty služby budete mít možnost vytvořit určitý počet účtů, které mezi sebou budou moci sídlet data. Každý účet má k dispozici soukromou část a sdílenou část s libovolným počtem uživatelů. Dále můžete využít firemní sidílený prostor</p>

<p>
Služba funguje tak že je stanoven správce pronajmuté služby, který se stará o vytváření účtů, přidělování práv a další věci spojené s fungováním datového uložiště.
</p>

<p>
Každý uživatel má k dispozici firemní prostor ve kterém může prohlížet, editovat, vytvářet soubory podle nastaveného oprávnění. Dále může sdílet soukromé soubory s ostatními uživateli. Možnosti záleží na oprávnění sdílení.
</p>

<p>
Sdílený prostor je dostupný na těchto platformách: Windows, Linux, Mac, iOS, Linux, Android, Windows phone.
</p>

<h1>Seznam variant datového uložiště</h1>
<table class="table">

	<thead>
				<tr>
					<th class="col-md-4">Parametry</th>
					<th class="col-md-2">Basic</th>
					<th class="col-md-2">Clasic</th>
					<th class="col-md-2">Standard</th>
					<th class="col-md-2">Premium</th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td class="col-md-4">Celková velikost</td>
					<td class="col-md-2">50 GB</td>
					<td class="col-md-2">100 GB</td>
					<td class="col-md-2">150 GB</td>
					<td class="col-md-2">500 GB</td>
				</tr>

				<tr>
					<td class="col-md-4">Počet účtů</td>
					<td class="col-md-2">100</td>
					<td class="col-md-2">500</td>
					<td class="col-md-2">1 000</td>
					<td class="col-md-2">Neomezený</td>
				</tr>

				<tr>
					<td class="col-md-4">Zálohování</td>
					<td class="col-md-2">Manuální</td>
					<td class="col-md-2">Manuální</td>
					<td class="col-md-2">Automatické</td>
					<td class="col-md-2">Automatické</td>
				</tr>

				<tr>
				<td class="col-md-4">Cena</td>
				<td class="col-md-2">5 000 Kč</td>
				<td class="col-md-2">9 000 Kč</td>
				<td class="col-md-2">15 000 Kč</td>
				<td class="col-md-2">28 000 Kč</td>
			</tr>
			</tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<h3><%= link_to 'Zákazníci', customers_path %></h3>
<h3><%= link_to 'Obědnávky', invoices_path %></h3>

app/views/home/welcome.html.erb
<h1>Welcome</h1>

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id, 'Zákazník' %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :date_created, 'Datum vytvoření' %><br>
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :date, 'Datum' %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :payment_date, 'Datum pladby' %><br>
    <%= f.date_select :payment_date %>
  </div>
  <div class="field">
    <%= f.label :payment_type, 'Typ platby' %><br>
    <%= f.text_field :payment_type %>
  </div>
  <div class="field">
    <%= f.label :amount, 'Částka' %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :items, 'Položky' %><br>
    <%= f.text_field :items %>
  </div>
  <div class="field">
    <%= f.label :note, 'Poznámka' %><br>
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit 'Odeslat' %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Zobrazit', @invoice %> |
<%= link_to 'Zpět', invoices_path %>

app/views/invoices/index.html.erb
<h1>Přehled obědnávek</h1>

<table>
  <thead>
    <tr>
      <th>Zákazník</th>
      <th>Datum vytvoření</th>
      <th>Typ platby</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.user_id %></td>
        <td><%= invoice.date_created %></td>
        <td><%= invoice.payment_date %></td>
        <td><%= invoice.amount %></td>
        <td><%= link_to 'Zobrazit', invoice %></td>
        <td><%= link_to 'Upravit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Smazat', invoice, method: :delete, data: { confirm: 'Opravdu chcete pkračovat?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nová objednávka', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>Nová obědnávka</h1>

<%= render 'form' %>

<%= link_to 'Zpět', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zákazník:</strong>
  <%= @invoice.user_id %>
</p>

<p>
  <strong>Datum vytvoření:</strong>
  <%= @invoice.date_created %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Datum pladby:</strong>
  <%= @invoice.payment_date %>
</p>

<p>
  <strong>Typ pladby:</strong>
  <%= @invoice.payment_type %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong>Položky:</strong>
  <%= @invoice.items %>
</p>

<p>
  <strong>Poznámka:</strong>
  <%= @invoice.note %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/_footer.html.erb
<%= mail_to "trol@IwasBEEN.here", "Cloud, s. r. o." %> © 2012 © Copiright by <%= mail_to "fanatik@heroesofmemory.eu", "Fanatik" %>
</br>
Firma je zapsána ve veřejném rejstříku, oddíl oddíl B vložka xi58.

app/views/layouts/_sidebar.html.erb
<div>
		<h3>Navigace</h3>

<ul>
		<li><%= link_to "Home", root_path %></li>
         <li>Domácnosti</li>
         <li><%= link_to 'Firmy', companies_path %></li>
         <li><%= link_to 'Aplikace', nil %></li>
         <li><%= link_to "Napište nám", nil %></li>
         <li><%= link_to "Onás", nil %></li>
</ul>
	</div>

<div>
	<h3>Administrace</h3>
<ul>
	<li><%= link_to "Zaměstnanci", nil %></li>
                <li><%= link_to "Klienti", nil %></li>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :customer_id, 'Customer' %>
    <%= f.select :customer_id, options_for_select(Customer.all.collect{|customer| ["#{customer.name} #{customer.surname}", customer.id]}, @order.customer_id), include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer.name %></td>
        <td><%= order.note %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @order.note %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>